### ISSUE TITLE
Python script

### ISSUE THREAD

**Issue by alesaccoia** [methodmatters/harmonic_structure_of_music#1]
Hi, thanks for the contribution on R-bloggers! Could you add the python script(s) you used to the repo?

**Comment by methodmatters** [comment]
Thanks for reading! I can do this during the winter holiday - in 2 weeks or so. There are a bunch of notebooks - will clean them up a bit before posting them here!

**Comment by methodmatters** [comment]
hey there I've added the notebooks to the repo! There are 6 of them, and it's not particularly well-documented. However, it should be good enough to get you started!

I realized after I was done that there might be a more efficient way to call the Spotify API to get the same information with fewer requests. To look into, if that's the kind of thing that interests you!
